### ISSUE TITLE
Allow charset specification in request header

### ISSUE THREAD

**Issue by EPNW-Eric** [extrnode/extrnode#1]
I'm working with a http library to make my rpc calls.
Unfortunately, this library forces me to use `application\json; charset=utf8` instead of `application\json`.
This leads to extrnode rejecting my requests as in `validator.go` an exact match is forced:
https://github.com/extrnode/extrnode/blob/dc2190beffbb37930e6a7bf6628d669ff814b74a/internal/api/middlewares/validator.go#L29
It would be nice if extrnode could also allow `application\json; charset=utf8` or if it could just check if the content-type starts with  `application\json` and ignore the rest.

**Comment by rengen12** [comment]
Hi, @EPNW-Eric. Thanks
I fixed it. Can you recheck, please?

**Comment by EPNW-Eric** [comment]
Yes, now it works with my library!
Thanks for fixing so fast😄
